sudo: false
language: node_js
node_js:
  - "5.0"
  - "6"
cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run lint

after_success:
  - npm start

deploy:
  provider: heroku
  app: yourselfr
  api_key:
    secure: ae0ec196-6393-4462-ba41-a6b3c368cf7e
